'use client'

import { useEffect, useState } from 'react'
import { CheckCircle, XCircle, AlertCircle, Search, Sparkles, User, RefreshCw } from 'lucide-react'
import { apiSlice, endpoints } from '@/lib/apiSlice'

interface CommentaryRecord {
  id: number
  remark: string
  originalAiRemark: string | null
  isAiGenerated: boolean
  isEditedByHuman: boolean
  status: string
  reviewNotes: string | null
  studentId: number
  updatedAt: string
  student: {
    id: number
    firstName: string
    lastName: string
    registerNo: string
  }
}

export function CommentaryReview() {
  const [commentaries, setCommentaries] = useState<CommentaryRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState<string>('ALL')
  
  // Rejection modal/form state
  const [rejectingRecord, setRejectingRecord] = useState<CommentaryRecord | null>(null)
  const [rejectNotes, setRejectNotes] = useState('')
  const [submittingReview, setSubmittingReview] = useState(false)
  const [actionSuccess, setActionSuccess] = useState<string | null>(null)

  const fetchCommentaries = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await apiSlice.get<{ success: boolean; commentaries: CommentaryRecord[] }>(
        endpoints.admin.pendingCommentaries
      )
      if (res.success) {
        setCommentaries(res.commentaries)
      }
    } catch (err: any) {
      setError(err.message || 'Failed to load commentaries pending review.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchCommentaries()
  }, [])

  const handleSignOff = async (commentaryId: number) => {
    setSubmittingReview(true)
    setError(null)
    try {
      const res = await apiSlice.post<{ success: boolean; message: string }>(
        endpoints.admin.reviewCommentary,
        {
          commentaryId,
          status: 'PRINCIPAL_SIGNED_OFF'
        }
      )
      if (res.success) {
        setActionSuccess('Commentary signed off and approved for report card.')
        fetchCommentaries()
        setTimeout(() => setActionSuccess(null), 3000)
      }
    } catch (err: any) {
      setError(err.message || 'Failed to sign off commentary.')
    } finally {
      setSubmittingReview(false)
    }
  }

  const handleRejectSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!rejectingRecord) return
    if (!rejectNotes.trim()) {
      alert('Please provide review notes explaining the rejection.')
      return
    }

    setSubmittingReview(true)
    setError(null)
    try {
      const res = await apiSlice.post<{ success: boolean; message: string }>(
        endpoints.admin.reviewCommentary,
        {
          commentaryId: rejectingRecord.id,
          status: 'REJECTED',
          reviewNotes: rejectNotes
        }
      )
      if (res.success) {
        setActionSuccess('Commentary returned to teacher with review notes.')
        setRejectingRecord(null)
        setRejectNotes('')
        fetchCommentaries()
        setTimeout(() => setActionSuccess(null), 3000)
      }
    } catch (err: any) {
      setError(err.message || 'Failed to reject commentary.')
    } finally {
      setSubmittingReview(false)
    }
  }

  const filteredCommentaries = commentaries.filter(c => {
    const fullName = `${c.student.firstName} ${c.student.lastName}`.toLowerCase()
    const matchesSearch = fullName.includes(searchQuery.toLowerCase()) || 
                          (c.student.registerNo && c.student.registerNo.toLowerCase().includes(searchQuery.toLowerCase()))
    
    if (statusFilter === 'ALL') return matchesSearch
    return matchesSearch && c.status === statusFilter
  })

  return (
    <div className="space-y-6">
      <div className="relative rounded-2xl bg-gradient-to-r from-violet-800 via-purple-700 to-indigo-800 p-6 md:p-8 shadow-md overflow-hidden text-white">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute right-0 top-0 w-80 h-80 bg-white/10 rounded-full blur-3xl opacity-40" />
        </div>
        <div className="relative z-10 space-y-2.5">
          <span className="px-2.5 py-1 text-xs font-bold bg-white/20 rounded-full border border-white/30 shadow-sm inline-block">
            Principal Review Desk
          </span>
          <h1 className="text-3xl font-extrabold tracking-tight">AI Commentary Oversight</h1>
          <p className="text-white/80 text-sm max-w-xl font-medium">
            Review, audit and authorize qualitative report card commentary generated by AI and approved by teachers.
          </p>
        </div>
      </div>

      {actionSuccess && (
        <div className="p-4 bg-emerald-50 border border-emerald-200 text-emerald-800 rounded-xl flex items-center gap-2 text-sm font-semibold shadow-xs">
          <CheckCircle size={18} className="text-emerald-600" />
          {actionSuccess}
        </div>
      )}

      {error && (
        <div className="p-4 bg-rose-50 border border-rose-200 text-rose-800 rounded-xl flex items-center gap-2 text-sm font-semibold shadow-xs">
          <AlertCircle size={18} className="text-rose-600" />
          {error}
        </div>
      )}

      {/* Filters and Search toolbar */}
      <div className="flex flex-col md:flex-row gap-4 justify-between items-center bg-white p-4 rounded-xl border border-slate-200/80 shadow-xs">
        <div className="relative w-full md:w-80">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by student name or reg no..."
            className="w-full pl-9 pr-4 py-2 rounded-lg border border-slate-200 bg-slate-50 text-slate-700 placeholder-slate-400 text-sm focus:outline-none focus:border-violet-500 focus:bg-white transition font-medium"
          />
        </div>

        <div className="flex items-center gap-2 w-full md:w-auto overflow-x-auto pb-1 md:pb-0">
          {['ALL', 'TEACHER_APPROVED', 'PRINCIPAL_SIGNED_OFF', 'REJECTED', 'DRAFT'].map((status) => (
            <button
              key={status}
              onClick={() => setStatusFilter(status)}
              className={`px-3 py-1.5 text-xs font-bold rounded-lg border transition whitespace-nowrap cursor-pointer ${
                statusFilter === status
                  ? 'bg-violet-600 border-violet-600 text-white shadow-3xs'
                  : 'bg-white border-slate-200 text-slate-600 hover:bg-slate-50'
              }`}
            >
              {status === 'ALL' && 'All'}
              {status === 'TEACHER_APPROVED' && 'Pending Review'}
              {status === 'PRINCIPAL_SIGNED_OFF' && 'Signed Off'}
              {status === 'REJECTED' && 'Rejected'}
              {status === 'DRAFT' && 'Draft (Not Saved)'}
            </button>
          ))}
          <button
            onClick={fetchCommentaries}
            disabled={loading}
            className="p-2 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg border border-slate-200 transition shrink-0 cursor-pointer"
            title="Refresh List"
          >
            <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
          </button>
        </div>
      </div>

      {/* Main listing */}
      {loading ? (
        <div className="flex flex-col items-center justify-center p-12 bg-white rounded-xl border border-slate-200/80 shadow-xs gap-3">
          <div className="w-8 h-8 border-4 border-violet-200 border-t-violet-600 rounded-full animate-spin" />
          <p className="text-slate-500 text-sm font-semibold animate-pulse">Loading commentary records...</p>
        </div>
      ) : filteredCommentaries.length === 0 ? (
        <div className="text-center p-12 bg-white rounded-xl border border-slate-200/80 shadow-xs">
          <AlertCircle className="mx-auto text-slate-300 mb-3" size={32} />
          <h3 className="font-extrabold text-slate-800 text-base">No Commentary Records</h3>
          <p className="text-slate-500 text-xs font-medium max-w-sm mx-auto mt-1">
            No commentaries matched your filter criteria. Let teachers draft and approve commentaries first.
          </p>
        </div>
      ) : (
        <div className="grid md:grid-cols-2 gap-6">
          {filteredCommentaries.map((record) => (
            <div key={record.id} className="bg-white border border-slate-200/80 rounded-xl p-5 shadow-xs flex flex-col justify-between gap-4">
              <div className="space-y-3.5">
                {/* Header */}
                <div className="flex items-center justify-between gap-2 border-b border-slate-100 pb-2.5">
                  <div className="flex items-center gap-2">
                    <div className="p-2 bg-violet-50 rounded-lg text-violet-600">
                      <User size={16} />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-slate-800">
                        {record.student.lastName}, {record.student.firstName}
                      </h4>
                      <p className="text-[10px] text-slate-400 font-semibold">Reg No: {record.student.registerNo}</p>
                    </div>
                  </div>

                  {/* Status Badge */}
                  {(() => {
                    switch (record.status) {
                      case 'PRINCIPAL_SIGNED_OFF':
                        return (
                          <span className="px-2 py-0.5 text-[10px] font-bold text-emerald-700 bg-emerald-50 rounded-md border border-emerald-100 shadow-3xs">
                            Signed Off
                          </span>
                        )
                      case 'TEACHER_APPROVED':
                        return (
                          <span className="px-2 py-0.5 text-[10px] font-bold text-blue-700 bg-blue-50 rounded-md border border-blue-100 shadow-3xs">
                            Pending Review
                          </span>
                        )
                      case 'REJECTED':
                        return (
                          <span className="px-2 py-0.5 text-[10px] font-bold text-rose-700 bg-rose-50 rounded-md border border-rose-100 shadow-3xs">
                            Rejected
                          </span>
                        )
                      default:
                        return (
                          <span className="px-2 py-0.5 text-[10px] font-bold text-amber-700 bg-amber-50 rounded-md border border-amber-100 shadow-3xs">
                            Draft
                          </span>
                        )
                    }
                  })()}
                </div>

                {/* Audit & Edit Comparison Section */}
                {record.isAiGenerated && record.originalAiRemark && record.isEditedByHuman ? (
                  <div className="grid grid-cols-1 gap-3.5 bg-slate-50/60 p-3 rounded-lg border border-slate-100 text-xs">
                    <div className="space-y-1">
                      <span className="text-[9px] font-extrabold uppercase tracking-wider text-slate-400 flex items-center gap-1">
                        🤖 Original AI Draft
                      </span>
                      <p className="text-slate-500 italic leading-relaxed font-semibold">
                        "{record.originalAiRemark}"
                      </p>
                    </div>
                    <div className="border-t border-slate-200/60 pt-2 space-y-1">
                      <span className="text-[9px] font-extrabold uppercase tracking-wider text-blue-600 flex items-center gap-1">
                        ✏️ Teacher Override (Final Submission)
                      </span>
                      <p className="text-slate-800 font-bold leading-relaxed">
                        "{record.remark}"
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="bg-slate-50/40 p-3 rounded-lg border border-slate-100 text-xs">
                    <div className="space-y-1">
                      <span className="text-[9px] font-extrabold uppercase tracking-wider text-slate-400 flex items-center gap-1">
                        {record.isAiGenerated ? '🤖 Pure AI Draft (Unchanged)' : '🧑‍🏫 Instructor Drafted Remark'}
                      </span>
                      <p className="text-slate-800 font-bold leading-relaxed">
                        "{record.remark}"
                      </p>
                    </div>
                  </div>
                )}

                {/* Rejection/Review notes banner */}
                {record.status === 'REJECTED' && record.reviewNotes && (
                  <div className="p-2.5 bg-rose-50/60 border border-rose-100 rounded-lg text-[11px] font-semibold text-rose-800">
                    <strong>Rejection Reason:</strong> {record.reviewNotes}
                  </div>
                )}
              </div>

              {/* Actions Footer */}
              {record.status === 'TEACHER_APPROVED' && (
                <div className="flex gap-2 border-t border-slate-100 pt-3">
                  <button
                    onClick={() => setRejectingRecord(record)}
                    disabled={submittingReview}
                    className="flex-1 inline-flex items-center justify-center gap-1 px-3 py-2 border border-rose-200 hover:bg-rose-50 text-rose-700 font-extrabold text-xs rounded-lg transition cursor-pointer"
                  >
                    <XCircle size={14} /> Reject
                  </button>
                  <button
                    onClick={() => handleSignOff(record.id)}
                    disabled={submittingReview}
                    className="flex-1 inline-flex items-center justify-center gap-1 px-3 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-xs rounded-lg shadow-sm transition cursor-pointer"
                  >
                    <CheckCircle size={14} /> Sign Off / Approve
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Reject Reason Modal Dialog */}
      {rejectingRecord && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl p-6 shadow-xl border border-slate-100 max-w-md w-full space-y-4 animate-in fade-in zoom-in duration-200">
            <div className="flex items-center gap-2 text-rose-600">
              <AlertCircle size={20} />
              <h3 className="text-base font-black">Reject Student Commentary</h3>
            </div>
            
            <p className="text-xs text-slate-500 font-semibold leading-relaxed">
              Explain why this commentary is rejected so the form teacher can revise it:
            </p>

            <form onSubmit={handleRejectSubmit} className="space-y-4">
              <textarea
                value={rejectNotes}
                onChange={(e) => setRejectNotes(e.target.value)}
                placeholder="e.g. Please refine the academic tone or correct spelling..."
                rows={3}
                required
                className="w-full px-3 py-2 text-sm font-semibold bg-slate-50 border border-slate-200 rounded-lg focus:ring-1 focus:ring-rose-500 focus:outline-none resize-none"
              />

              <div className="flex gap-3">
                <button
                  type="button"
                  onClick={() => {
                    setRejectingRecord(null)
                    setRejectNotes('')
                  }}
                  disabled={submittingReview}
                  className="flex-1 px-3 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs rounded-xl transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submittingReview}
                  className="flex-1 px-3 py-2 bg-rose-600 hover:bg-rose-700 text-white font-bold text-xs rounded-xl transition shadow-sm"
                >
                  {submittingReview ? 'Submitting...' : 'Confirm Rejection'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}
