'use client'

import { useState } from 'react'
import {
  BookOpen,
  Sparkles,
  Calendar,
  CheckCircle2,
  XCircle,
  Clock,
  Search,
  FileText,
  Download,
  Loader2,
  Bot,
  Plus,
  Send,
  Edit3,
  Award,
  Check,
  AlertCircle,
  HelpCircle,
  FileCheck
} from 'lucide-react'
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
  TableCaption,
} from '@/components/ui/table'

type LessonTab = 'ai-notes' | 'scheme-of-work' | 'weekly-planner' | 'lesson-approval'

interface LessonNoteItem {
  id: string
  subject: string
  classLevel: string
  topic: string
  teacherName: string
  submittedDate: string
  status: 'approved' | 'pending' | 'revision'
}

export function LessonManagement() {
  const [activeTab, setActiveTab] = useState<LessonTab>('ai-notes')

  // AI Lesson Generator State
  const [aiSubject, setAiSubject] = useState('Mathematics')
  const [aiClass, setAiClass] = useState('Primary 4')
  const [aiTopic, setAiTopic] = useState('Fractions & Decimals')
  const [aiDuration, setAiDuration] = useState('40 Minutes')
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedNote, setGeneratedNote] = useState<string | null>(null)

  // Lesson Notes Approval Roster State
  const [lessonNotes, setLessonNotes] = useState<LessonNoteItem[]>([
    { id: 'LSN-101', subject: 'Mathematics', classLevel: 'Primary 4', topic: 'Fractions & Decimals', teacherName: 'Mrs. Victoria Adams', submittedDate: '2026-08-01', status: 'approved' },
    { id: 'LSN-102', subject: 'English Language', classLevel: 'Primary 5', topic: 'Nouns & Adjectives in Context', teacherName: 'Mr. Christopher Williams', submittedDate: '2026-08-01', status: 'pending' },
    { id: 'LSN-103', subject: 'Basic Science', classLevel: 'Primary 3', topic: 'Living & Non-Living Things', teacherName: 'Mrs. Florence Eze', submittedDate: '2026-07-31', status: 'pending' },
    { id: 'LSN-104', subject: 'Physics', classLevel: 'SSS 1', topic: 'Newtonian Laws of Motion', teacherName: 'Dr. Samuel Biobaku', submittedDate: '2026-07-30', status: 'approved' },
    { id: 'LSN-105', subject: 'Financial Accounting', classLevel: 'SSS 2', topic: 'Trial Balance & Ledger Accounts', teacherName: 'Mr. Gabriel Okoro', submittedDate: '2026-07-29', status: 'revision' },
  ])

  const handleGenerateAiNote = (e: React.FormEvent) => {
    e.preventDefault()
    if (!aiTopic) return

    setIsGenerating(true)
    setTimeout(() => {
      setGeneratedNote(`
# LESSON NOTE: ${aiTopic.toUpperCase()}
**Subject**: ${aiSubject} | **Class**: ${aiClass} | **Duration**: ${aiDuration}

---
### 🎯 1. LESSON OBJECTIVES
By the end of this lesson, pupils should be able to:
1. Define and identify proper and improper fractions with 90% accuracy.
2. Convert mixed fractions into improper decimals cleanly.
3. Solve 5 practical real-life word problems involving fraction addition.

---
### 📚 2. INSTRUCTIONAL MATERIALS
- Visual Fraction Wall Charts & Cutouts
- Interactive Digital Classroom Board
- Student Mathematics Workbook (Page 45 - 48)

---
### 🚀 3. LESSON PRESENTATION & PROCEDURE
- **Step 1 (Introduction - 5 mins)**: Review previous lesson on basic division. Ask pupils to divide 1 pizza among 4 friends.
- **Step 2 (Core Content - 20 mins)**: Demonstrate numerator and denominator concepts using visual slice cards. Write key rules on board.
- **Step 3 (Guided Practice - 10 mins)**: Solve 3 board examples together with pupil participation.

---
### ✍️ 4. EVALUATION & CLASSWORK
1. What is 3/4 + 1/4?
2. Convert 2 1/2 into an improper fraction.
3. If Kemi eats 2/5 of a cake, what fraction remains?

*Generated by OSe AI Engine • NERDC National Curriculum Compliant*
      `)
      setIsGenerating(false)
    }, 1000)
  }

  const handleUpdateStatus = (id: string, status: 'approved' | 'revision') => {
    setLessonNotes(prev => prev.map(l => l.id === id ? { ...l, status } : l))
  }

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="relative rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute right-0 top-0 w-64 h-64 bg-emerald-50/60 rounded-full blur-3xl opacity-60" />
        </div>
        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <h1 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
              <BookOpen className="text-emerald-600" size={24} /> Lesson Management Suite
            </h1>
            <p className="text-slate-500 text-sm font-medium">
              AI-powered lesson note generation, scheme of work tracking, weekly planners, and supervisor lesson approval.
            </p>
          </div>

          <button
            onClick={() => setActiveTab('ai-notes')}
            className="px-4 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs shadow-sm flex items-center gap-2 transition cursor-pointer self-start md:self-auto shrink-0"
          >
            <Sparkles size={15} className="text-amber-400" /> AI Note Generator
          </button>
        </div>
      </div>

      {/* Tabs Navigation */}
      <div className="flex items-center gap-2 overflow-x-auto p-1.5 bg-white border border-slate-200/80 rounded-2xl shadow-2xs">
        <button
          onClick={() => setActiveTab('ai-notes')}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl font-bold text-xs transition cursor-pointer shrink-0 ${
            activeTab === 'ai-notes' ? 'bg-emerald-600 text-white shadow-xs' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <Sparkles size={15} className="text-amber-300" /> AI Lesson Notes
        </button>

        <button
          onClick={() => setActiveTab('scheme-of-work')}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl font-bold text-xs transition cursor-pointer shrink-0 ${
            activeTab === 'scheme-of-work' ? 'bg-emerald-600 text-white shadow-xs' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <BookOpen size={15} /> Scheme of Work
        </button>

        <button
          onClick={() => setActiveTab('weekly-planner')}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl font-bold text-xs transition cursor-pointer shrink-0 ${
            activeTab === 'weekly-planner' ? 'bg-emerald-600 text-white shadow-xs' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <Calendar size={15} /> Weekly Planner
        </button>

        <button
          onClick={() => setActiveTab('lesson-approval')}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl font-bold text-xs transition cursor-pointer shrink-0 ${
            activeTab === 'lesson-approval' ? 'bg-emerald-600 text-white shadow-xs' : 'text-slate-600 hover:bg-slate-100'
          }`}
        >
          <CheckCircle2 size={15} /> Lesson Approval
        </button>
      </div>

      {/* TAB 1: AI LESSON NOTES */}
      {activeTab === 'ai-notes' && (
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Left 1/3: Generator Controls */}
          <div className="bg-white rounded-2xl border border-slate-200/80 p-5 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
              <Bot size={20} className="text-amber-500" />
              <div>
                <h3 className="font-black text-xs text-slate-900 uppercase tracking-wider">OSe AI Lesson Note Engine</h3>
                <p className="text-[11px] text-slate-400 font-medium">Generate curriculum-aligned lesson plans in seconds.</p>
              </div>
            </div>

            <form onSubmit={handleGenerateAiNote} className="space-y-3">
              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Subject Discipline</label>
                <select
                  value={aiSubject}
                  onChange={e => setAiSubject(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs font-semibold bg-slate-50"
                >
                  <option value="Mathematics">Mathematics</option>
                  <option value="English Language">English Language</option>
                  <option value="Basic Science">Basic Science</option>
                  <option value="Computer Studies">Computer Studies / ICT</option>
                  <option value="Physics">Physics</option>
                  <option value="Financial Accounting">Financial Accounting</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Target Class Level</label>
                <select
                  value={aiClass}
                  onChange={e => setAiClass(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs font-semibold bg-slate-50"
                >
                  <option value="Primary 1">Primary 1</option>
                  <option value="Primary 2">Primary 2</option>
                  <option value="Primary 3">Primary 3</option>
                  <option value="Primary 4">Primary 4</option>
                  <option value="Primary 5">Primary 5</option>
                  <option value="JSS 1">JSS 1</option>
                  <option value="SSS 1">SSS 1</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Topic Title</label>
                <input
                  type="text"
                  placeholder="e.g. Fractions & Decimals"
                  value={aiTopic}
                  onChange={e => setAiTopic(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs font-semibold bg-slate-50"
                  required
                />
              </div>

              <div>
                <label className="text-xs font-bold text-slate-700 block mb-1">Lesson Duration</label>
                <input
                  type="text"
                  placeholder="40 Minutes"
                  value={aiDuration}
                  onChange={e => setAiDuration(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs font-semibold bg-slate-50"
                />
              </div>

              <button
                type="submit"
                disabled={isGenerating}
                className="w-full py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs transition cursor-pointer flex items-center justify-center gap-2 shadow-xs"
              >
                {isGenerating ? <Loader2 size={14} className="animate-spin text-amber-400" /> : <Sparkles size={14} className="text-amber-400" />} Generate Complete Lesson Note
              </button>
            </form>
          </div>

          {/* Right 2/3: Generated Note Display */}
          <div className="lg:col-span-2 bg-white rounded-2xl border border-slate-200/80 p-6 shadow-sm flex flex-col justify-between space-y-4 min-h-[460px]">
            {generatedNote ? (
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                  <span className="px-2.5 py-1 rounded-lg bg-emerald-50 text-emerald-700 border border-emerald-200 font-extrabold text-xs">
                    ✓ OSe AI Generated Note
                  </span>
                  <button
                    onClick={() => alert('Exporting Lesson Note to PDF...')}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs rounded-lg transition"
                  >
                    <Download size={13} /> Export PDF
                  </button>
                </div>
                <div className="p-4 bg-slate-50/70 rounded-xl border border-slate-200 font-mono text-xs text-slate-800 whitespace-pre-wrap leading-relaxed max-h-[380px] overflow-y-auto">
                  {generatedNote}
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center my-auto py-16 text-center text-slate-400 space-y-2">
                <Sparkles size={32} className="text-slate-300" />
                <p className="text-xs font-bold text-slate-600">No Lesson Note Generated Yet</p>
                <p className="text-[11px] text-slate-400 max-w-sm">Enter a topic on the left panel and click "Generate Complete Lesson Note" to generate an OSe AI lesson plan.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* TAB 2: SCHEME OF WORK */}
      {activeTab === 'scheme-of-work' && (
        <div className="bg-white rounded-2xl border border-slate-200/80 p-6 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div>
              <h3 className="font-black text-base text-slate-900 flex items-center gap-2">
                <BookOpen className="text-emerald-600" size={20} /> Termly Scheme of Work (12 Weeks)
              </h3>
              <p className="text-xs text-slate-500 font-medium">1st Term Academic Syllabus breakdown aligned with national NERDC standards.</p>
            </div>
          </div>

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Week</TableHead>
                <TableHead>Topic Title</TableHead>
                <TableHead>Learning Objectives</TableHead>
                <TableHead>Teacher Learning Aids</TableHead>
                <TableHead className="text-right">Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {[
                { week: 'Week 1', topic: 'Revision & Diagnostic Test', obj: 'Assess pupil entry knowledge', aids: 'Question Cards', status: 'Completed' },
                { week: 'Week 2', topic: 'Fractions & Decimals', obj: 'Understand proper & improper fractions', aids: 'Fraction Charts', status: 'Completed' },
                { week: 'Week 3', topic: 'Addition of Like Fractions', obj: 'Solve like fraction additions', aids: 'Visual Boards', status: 'In Progress' },
                { week: 'Week 4', topic: 'Subtraction of Unlike Fractions', obj: 'Find LCM and subtract fractions', aids: 'Worksheets', status: 'Upcoming' },
                { week: 'Week 5', topic: 'Decimals & Percentages', obj: 'Convert decimals into percentages', aids: 'Digital Charts', status: 'Upcoming' },
              ].map((row, idx) => (
                <TableRow key={idx}>
                  <TableCell className="font-mono font-black text-emerald-700">{row.week}</TableCell>
                  <TableCell className="font-bold text-slate-900">{row.topic}</TableCell>
                  <TableCell className="text-xs text-slate-600">{row.obj}</TableCell>
                  <TableCell className="text-xs font-medium text-slate-700">{row.aids}</TableCell>
                  <TableCell className="text-right">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-extrabold ${
                      row.status === 'Completed' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' :
                      row.status === 'In Progress' ? 'bg-amber-50 text-amber-700 border border-amber-200' : 'bg-slate-100 text-slate-600'
                    }`}>
                      {row.status}
                    </span>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}

      {/* TAB 3: WEEKLY PLANNER */}
      {activeTab === 'weekly-planner' && (
        <div className="bg-white rounded-2xl border border-slate-200/80 p-6 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div>
              <h3 className="font-black text-base text-slate-900 flex items-center gap-2">
                <Calendar className="text-emerald-600" size={20} /> Teacher Weekly Lesson Planner
              </h3>
              <p className="text-xs text-slate-500 font-medium">Day-by-day timetable schedule and classroom activity planning.</p>
            </div>
          </div>

          <div className="grid md:grid-cols-5 gap-3">
            {['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'].map((day, idx) => (
              <div key={day} className="p-4 rounded-2xl border border-slate-200 bg-slate-50/70 space-y-2">
                <h4 className="font-black text-xs text-slate-900 uppercase border-b border-slate-200 pb-1.5">{day}</h4>
                <div className="p-2.5 bg-white rounded-xl border border-slate-200 text-xs space-y-1 shadow-2xs">
                  <p className="font-bold text-slate-900">Period 1 (08:30 AM)</p>
                  <p className="text-[11px] text-emerald-700 font-semibold">Mathematics • Primary 4</p>
                  <p className="text-[10px] text-slate-500">Topic: Fractions</p>
                </div>
                <div className="p-2.5 bg-white rounded-xl border border-slate-200 text-xs space-y-1 shadow-2xs">
                  <p className="font-bold text-slate-900">Period 4 (11:00 AM)</p>
                  <p className="text-[11px] text-blue-700 font-semibold">Basic Science • Primary 3</p>
                  <p className="text-[10px] text-slate-500">Topic: Living Things</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 4: LESSON APPROVAL */}
      {activeTab === 'lesson-approval' && (
        <div className="bg-white rounded-2xl border border-slate-200/80 p-6 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div>
              <h3 className="font-black text-base text-slate-900 flex items-center gap-2">
                <CheckCircle2 className="text-emerald-600" size={20} /> Principal & Supervisor Lesson Note Approval
              </h3>
              <p className="text-xs text-slate-500 font-medium">Audit teacher lesson notes, approve plans, or send back revision requests.</p>
            </div>
          </div>

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Ref ID</TableHead>
                <TableHead>Teacher Name</TableHead>
                <TableHead>Subject Discipline</TableHead>
                <TableHead>Class Level</TableHead>
                <TableHead>Topic Title</TableHead>
                <TableHead>Submitted Date</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Approval Decision</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {lessonNotes.map((note) => (
                <TableRow key={note.id}>
                  <TableCell className="font-mono font-bold text-slate-700">{note.id}</TableCell>
                  <TableCell className="font-bold text-slate-900">{note.teacherName}</TableCell>
                  <TableCell className="text-xs font-semibold text-slate-700">{note.subject}</TableCell>
                  <TableCell className="text-xs text-slate-600">{note.classLevel}</TableCell>
                  <TableCell className="font-semibold text-slate-800">{note.topic}</TableCell>
                  <TableCell className="text-xs text-slate-500">{note.submittedDate}</TableCell>
                  <TableCell>
                    <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-extrabold uppercase ${
                      note.status === 'approved' ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' :
                      note.status === 'pending' ? 'bg-amber-50 text-amber-700 border border-amber-200' : 'bg-rose-50 text-rose-700 border border-rose-200'
                    }`}>
                      {note.status}
                    </span>
                  </TableCell>
                  <TableCell className="text-right space-x-1">
                    <button
                      onClick={() => handleUpdateStatus(note.id, 'approved')}
                      className="px-2.5 py-1 text-[11px] font-bold text-emerald-700 bg-emerald-50 hover:bg-emerald-100 rounded-lg transition cursor-pointer"
                    >
                      Approve
                    </button>
                    <button
                      onClick={() => handleUpdateStatus(note.id, 'revision')}
                      className="px-2.5 py-1 text-[11px] font-bold text-amber-700 bg-amber-50 hover:bg-amber-100 rounded-lg transition cursor-pointer"
                    >
                      Request Revision
                    </button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}
    </div>
  )
}
